apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "static.fullname" . }}
  labels:
    {{- include "static.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "static.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "static.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
