apiVersion: v1
kind: Service
metadata:
  name: {{ include "static.fullname" . }}
  labels:
    {{- include "static.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "static.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: http
      name: http
